#!/bin/sh

HOME=${application.home}
JMX_PORT=${application.jmx.port}
DEBUG_PORT=${application.debug.port}
LOG_DIR=${log.dir}
MAIN=${application.main}
DAEMON=${application.daemon.enable}
CONSOLE_LOG=\${LOG_DIR}/${application.name}-console.log
CLASSPATH=\${HOME}/conf:\${HOME}/lib/${application.name}-all.jar
JAVA_OPTIONS="-server -Xmx${application.heapsize}\
  -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=\${LOG_DIR}/java_$$.hprof\
  -XX:+UseConcMarkSweepGC -XX:+UseParNewGC\
  -verbose:gc -Xloggc:\${LOG_DIR}/gc.log\
  -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime\
  -XX:+PrintGCApplicationConcurrentTime -XX:+PrintTenuringDistribution\
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=\${DEBUG_PORT}\
  -Djava.rmi.server.hostname=`hostname`\
  -Dcom.sun.management.jmxremote=true\
  -Dcom.sun.management.jmxremote.port=\${JMX_PORT}\
  -Dcom.sun.management.jmxremote.ssl=false\
  -Dcom.sun.management.jmxremote.authenticate=false\
  -Dlogback.configurationFile=\${HOME}/conf/logback.xml"
export JAVA_HOME=\${JAVA_HOME:-/usr/java/default}

if [ "$DAEMON" = "true" ]; then
  run_as="chpst -u ${application.user}:${application.group}"
fi

echo exec $run_as \${JAVA_HOME}/bin/java \${JAVA_OPTIONS} -cp \${CLASSPATH} \${MAIN} 1>>\${CONSOLE_LOG} 2>&1